[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
buildCommand = "npm run build"
healthcheckPath = "/api/v1/clients"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
